//
// Created by wq on 2020/12/13.
//

#include <random>
#include <iostream>

int main()
{
    {
        std::random_device rd;  //Will be used to obtain a seed for the random number engine
        std::mt19937 gen(rd()); //Standard mersenne_twister_engine seeded with rd()
        std::uniform_int_distribution<> distrib(1, 6);

        for (int n = 0; n < 10; ++n)
            //Use `distrib` to transform the random unsigned int generated by gen into an int in [1, 6]
            std::cout << distrib(gen) << ' ';
        std::cout << '\n';
    }
    {
        // fill the vectors with random numbers
        std::random_device rd;
        std::mt19937 mt(rd());
        std::uniform_real_distribution<> dis(0.0, 9.0);

        std::vector<float> v1(10);

        std::generate(v1.begin(), v1.end(), std::bind(dis, std::ref(mt)));

        // output v1
        std::cout << "v1 : ";
        std::copy(v1.begin(), v1.end(), std::ostream_iterator<float>(std::cout, " "));
        std::cout << '\n';

    }
}